### ISSUE TITLE
document AWS_REGION varaible (was etcd-aws-cfn: Missing region)

### ISSUE THREAD

**Issue by pboguk** [crewjam/etcd-aws#2]
Hi,

When I try to deploy CF via etcd-aws-cfn I get error:
 ERROR: deploy: MissingRegion: could not find region configuration

What the way to fix it?

Thank you

**Comment by crewjam** [comment]
The workaround is setting an environment variable `AWS_REGION=us-east-1` or whatever. Lets leave this bug open so I can update the README

**Comment by pboguk** [comment]
After setting variable AWS_REGION=us-east-1 I got another error:
etcd-aws-cfn -key-pair="keypair" -app="etcd-test-app" -dns-name="etcd.tesp.app"

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x636def]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/service/cloudformation.(_CloudFormation).newRequest(0x0, 0xc208312ec0, 0x8ec240, 0xc208243420, 0x8ec320, 0x0, 0x0)
        /root/go/src/github.com/aws/aws-sdk-go/service/cloudformation/service.go:95 +0x1f
github.com/aws/aws-sdk-go/service/cloudformation.(_CloudFormation).DescribeStackEventsRequest(0x0, 0xc208243420, 0x10, 0x0)
        /root/go/src/github.com/aws/aws-sdk-go/service/cloudformation/api.go:295 +0x293
github.com/aws/aws-sdk-go/service/cloudformation.(_CloudFormation).DescribeStackEventsPages(0x0, 0xc208243420, 0xc2082379a8, 0x0, 0x0)
        /root/go/src/github.com/aws/aws-sdk-go/service/cloudformation/api.go:314 +0x58
github.com/crewjam/go-cloudformation/deploycfn.(_StackEventWatcher).Watch(0xc208239080, 0x0, 0x0)
        /root/go/src/github.com/crewjam/go-cloudformation/deploycfn/watcher.go:94 +0x131
github.com/crewjam/go-cloudformation/deploycfn.Deploy(0x7f5161e32320, 0xc20809a000, 0xc208194b20, 0x11, 0xc20802e460, 0xc20803d0b0, 0x0, 0x0)
        /root/go/src/github.com/crewjam/go-cloudformation/deploycfn/deploycfn.go:129 +0xc82
main.Main(0x0, 0x0)
        /root/go/src/github.com/crewjam/etcd-aws/aws/etcd-aws-cfn/main.go:71 +0x789
main.main()
        /root/go/src/github.com/crewjam/etcd-aws/aws/etcd-aws-cfn/main.go:78 +0x1f

goroutine 9 [IO wait]:
net.(_pollDesc).Wait(0xc208010300, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc208010300, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc2080102a0, 0xc208052000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc2081dfbb8)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c078, 0xc208052000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc20803d8f0, 0x7f5161e336a8, 0xc20802c078, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc208050000, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc208050000, 0xc208053000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc208050000, 0xc208070108, 0xc208053000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc2081b0ee0, 0xc208053000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc208218a80)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc208218a80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc2080700b0)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [select]:
net/http.(_persistConn).writeLoop(0xc2080700b0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 14 [IO wait]:
net.(_pollDesc).Wait(0xc2081d4fb0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2081d4fb0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc2081d4f50, 0xc2080b9000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc20822e6f8)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c188, 0xc2080b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc2081cc270, 0x7f5161e336a8, 0xc20802c188, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc208051600, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc208051600, 0xc20825c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc208051600, 0xc2082149f8, 0xc20825c000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc208224700, 0xc20825c000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc2080304e0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc2080304e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc2082149a0)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 15 [select]:
net/http.(_persistConn).writeLoop(0xc2082149a0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 20 [IO wait]:
net.(_pollDesc).Wait(0xc2081d5fe0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2081d5fe0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc2081d5f80, 0xc20827a000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc20821d1a8)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c278, 0xc20827a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc2081cdce0, 0x7f5161e336a8, 0xc20802c278, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc208051b80, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc208051b80, 0xc20827b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc208051b80, 0xc208214d68, 0xc20827b000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc20820f960, 0xc20827b000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc20827cb40)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc20827cb40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc208214d10)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 21 [select]:
net/http.(_persistConn).writeLoop(0xc208214d10)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 51 [select]:
net/http.(_persistConn).writeLoop(0xc208215e40)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 50 [IO wait]:
net.(_pollDesc).Wait(0xc2083233a0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2083233a0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc208323340, 0xc20828c000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc20822ef58)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c210, 0xc20828c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc20822c630, 0x7f5161e336a8, 0xc20802c210, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc20828e580, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc20828e580, 0xc20828d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc20828e580, 0xc208215e98, 0xc20828d000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc20820eb40, 0xc20828d000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc2082f7020)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc2082f7020, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc208215e40)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 30 [IO wait]:
net.(_pollDesc).Wait(0xc2082b26f0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2082b26f0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc2082b2690, 0xc2082c2000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc2081c1098)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c438, 0xc2082c2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc208151ef0, 0x7f5161e336a8, 0xc20802c438, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc20828e840, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc20828e840, 0xc2082c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc20828e840, 0xc208215448, 0xc2082c3000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc20819b6c0, 0xc2082c3000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc2082b54a0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc2082b54a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc2082153f0)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 31 [select]:
net/http.(_persistConn).writeLoop(0xc2082153f0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 35 [IO wait]:
net.(_pollDesc).Wait(0xc2082b3330, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2082b3330, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc2082b32d0, 0xc2082cd000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc208198268)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c508, 0xc2082cd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc2080c2780, 0x7f5161e336a8, 0xc20802c508, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc20828edc0, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc20828edc0, 0xc2082f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc20828edc0, 0xc2082157b8, 0xc2082f0000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc208178e40, 0xc2082f0000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc2082f6ae0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc2082f6ae0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc208215760)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 36 [select]:
net/http.(_persistConn).writeLoop(0xc208215760)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 40 [IO wait]:
net.(_pollDesc).Wait(0xc2082b3f70, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2082b3f70, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc2082b3f10, 0xc208320000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc20818b0a8)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c5d8, 0xc208320000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc208314180, 0x7f5161e336a8, 0xc20802c5d8, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc20828f340, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc20828f340, 0xc208321000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc20828f340, 0xc208215b28, 0xc208321000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc208146200, 0xc208321000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc208332120)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc208332120, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc208215ad0)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 41 [select]:
net/http.(_persistConn).writeLoop(0xc208215ad0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 45 [IO wait]:
net.(_pollDesc).Wait(0xc208322760, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc208322760, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc208322700, 0xc208290000, 0x1000, 0x1000, 0x0, 0x7f5161e31ca8, 0xc208242178)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c108, 0xc208290000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc208314f00, 0x7f5161e336a8, 0xc20802c108, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc2080518c0, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc2080518c0, 0xc20827f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc2080518c0, 0xc208214318, 0xc20827f000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc208238b40, 0xc20827f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc2083337a0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc2083337a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc2082142c0)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 46 [select]:
net/http.(_persistConn).writeLoop(0xc2082142c0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 55 [IO wait]:
net.(_pollDesc).Wait(0xc208323fe0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc208323fe0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).Read(0xc208323f80, 0xc208317400, 0x400, 0x400, 0x0, 0x7f5161e31ca8, 0xc20820a300)
        /usr/lib/golang/src/net/fd_unix.go:242 +0x40f
net.(_conn).Read(0xc20802c2f8, 0xc208317400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:121 +0xdc
crypto/tls.(_block).readFromUntil(0xc2081cd350, 0x7f5161e336a8, 0xc20802c2f8, 0x5, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(_Conn).readRecord(0xc20828f080, 0x17, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(_Conn).Read(0xc20828f080, 0xc2081f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f5161e38068, 0xc20828f080, 0xc208070b58, 0xc2081f6000, 0x1000, 0x1000, 0x886b20, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1270 +0x6e
net/http.(_noteEOFReader).Read(0xc2081d2c20, 0xc2081f6000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(_Reader).fill(0xc2082b4ea0)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1ce
bufio.(_Reader).Peek(0xc2082b4ea0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:132 +0xf0
net/http.(_persistConn).readLoop(0xc208070b00)
        /usr/lib/golang/src/net/http/transport.go:842 +0xa4
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 56 [select]:
net/http.(_persistConn).writeLoop(0xc208070b00)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 60 [select]:
net/http.(_persistConn).readLoop(0xc2080711e0)
        /usr/lib/golang/src/net/http/transport.go:928 +0x9ce
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 61 [select]:
net/http.(_persistConn).writeLoop(0xc2080711e0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

goroutine 65 [runnable]:
net/http.(_persistConn).readLoop(0xc2080c9130)
        /usr/lib/golang/src/net/http/transport.go:928 +0x9ce
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 66 [select]:
net/http.(_persistConn).writeLoop(0xc2080c9130)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(_Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

Is any way to fix it?

**Comment by pboguk** [comment]
Seems was error with keypair name.
